apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: platform
spec:
  project: platform
  sources:
    - repoURL: "{{ .Values.source }}"
      targetRevision: HEAD
      ref: values
    - repoURL: "{{ .Values.source }}"
      path: cluster/namespaces
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/global.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
